# Generated by Django 5.1.1 on 2024-09-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_edit_title', 'can edit title'), ('can_edit_content', 'can edit content'), ('can_edit_is_published', 'can edit is_published')], 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
