# Generated by Django 5.0.7 on 2024-09-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_created_at_alter_product_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=2, default=0.01, help_text='Введите номер версии продукта', max_digits=4, verbose_name='Номер версии')),
                ('version_name', models.CharField(blank=True, help_text='Введите имя версии продукта', max_length=100, null=True, verbose_name='название версии')),
                ('is_active', models.BooleanField(default=False, help_text='Укажите является ли версия активной')),
                ('product', models.ForeignKey(default='empty', help_text='Выберите продукт', on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
                'ordering': ('version_name',),
            },
        ),
    ]
