# Generated by Django 5.1.1 on 2024-09-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_name',), 'permissions': [('can_edit_product_description', 'can edit product description'), ('can_edit_category', 'can edit category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ('version_name',), 'permissions': [('can_edit_is_active', 'can cancel publication')], 'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
    ]
